version: '3.4'

services:
  messageborkerservice:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmqmessagebroker
    hostname: rabbithost
    ports:
       - 5672:5672
       - 15672:15672
    networks: 
       - main 

  storageservice:
    image: minio/minio
    container_name: miniostorageservice
    hostname: minio
    command: server /data --console-address ":9001"
    volumes:
        - C:\Temp\Docker\Data\Minio:/data
    ports:
       - 9000:9000
       - 9001:9001
    networks: 
       - main 

  mapentitiesservice:
    image: ${DOCKER_REGISTRY-}mapentitiesservice
    build:
      context: .
      dockerfile: MapEntitiesService/Dockerfile
    depends_on:
      - messageborkerservice
    networks: 
      - main 
       
  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    depends_on:
      - messageborkerservice
    networks: 
      - main
      
  maprepositoryapi:
    image: ${DOCKER_REGISTRY-}maprepositoryapi
    volumes:
        - C:\Temp\Docker\Data:/app
    environment:
       - MINIO_ACCESS_KEY=t8LryXgHeC2u009qG2ja
       - MINIO_SECRET_KEY=DotuNClm0kRcqtrSNPJZwbcRYApBTykNzACx5onv
    build:
      context: .
      dockerfile: MapRepositoryAPI/Dockerfile
    networks: 
      - main

networks:
 main:
    name: "main"